repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -  id: trailing-whitespace
    -  id: end-of-file-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args:
        - "--max-line-length=120"
        - "--per-file-ignores=__init__.py:F401"
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      args:
        - --line-length=120
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
