version: "3.9"
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py createsuperuser --username ${SUPERUSERUSERNAME} --email ${SUPERUSEREMAIL} --no-input && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - dev.env
    volumes:
      - .:/valve_analytics_webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
volumes:
  postgres_data:
