version: "3.9"
services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/valve_analytics_webapp
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "${ANALYTICS_WEBAPP_DB_PASSWORD}"
      POSTGRES_USER: "${ANALYTICS_WEBAPP_DB_USER}"
    ports:
      - "5432:${ANALYTICS_WEBAPP_DB_PORT}"
volumes:
  postgres_data:
